server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间,5分钟
      idle-timeout: 300000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接的自动提交
      auto-commit: true
      #连接最大存活时间，30分钟
      max-lifetime: 1800000
      #连接超时时间，30秒
      connection-timeout: 30000
      #测试连接是否可用的查询
      connection-test-query: SELECT 1
  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 47.115.120.2
    #端口
    port: 6379
    #数据库
    database: 0
    #密码
    password: 190557
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  rabbitmq:
    username: guest
    password: guest
    host: 47.115.120.2
    port: 5672
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true

# mybatis-plus配置
mybatis-plus:
  #配置mapper映射文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  #配置别名
  type-aliases-package: com.pdd.pojo
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false

# Mybatis SQL 打印
logging:
  level:
    com.pdd.mapper: debug

#JWT
jwt:
#  存储的请求头
  tokenHeader: Authorization
#  加解密使用的密钥
  secret: wow-secret
#  过期时间60*60*24
  expiration: 604800
#  负载中拿到的开头
  tokenHead: Bearer