server:
  port: 8082

spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: utf-8
    password: ladgvcstnxtcbbeg
    username: 876085987@qq.com
    port: 25

  rabbitmq:
    username: guest
    password: guest
    host: 47.115.120.2
    port: 5672
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual

  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 47.115.120.2
    #端口
    port: 6379
    #数据库
    database: 0
    #密码
    password: 190557
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5